### ISSUE TITLE
There are no compatible challenges with protocols ['aido2_simple_predictor-z2'].

### ISSUE THREAD

**Issue by tanij** [duckietown/challenge-prediction#1]
Following the test submission docs: http://docs.duckietown.org/DT19/AIDO/out/cm_first.html

![image](https://user-images.githubusercontent.com/17256784/56127900-80a00700-5f7e-11e9-8512-fdb30666a338.png)

**Comment by tanij** [comment]
@AndreaCensi @liampaull

**Comment by AndreaCensi** [comment]
It was a permission issue. (worked for me and Liam...)

**Comment by noureldinalaa** [comment]
> It was a permission issue. (worked for me and Liam...)

i have the same issue now while trying to submit dummy submission  following this [link,](https://docs.duckietown.org/daffy/AIDO/out/cm_first.html)
 how can i get permission or how can i solve it please.
Thanks in advance
@AndreaCensi @liampaull

**Comment by fshamass** [comment]
Have the same issue. Was anyone able to figure out a solution?
